version: '3'
services:
  firebase:
    build:
      context: ./back/firebase
      dockerfile: ./Dockerfile-dev
    ports:
      - '4000:4000'
      - '9099:9099'
      - '8080:8080'
    command: firebase emulators:start --only auth,firestore

  gorila:
    build:
      context: ./front/apps/gorila
      dockerfile: ./Dockerfile-dev
    ports:
      - '8081:8081'
    container_name: gorila-app
    volumes:
      - ./front/apps/gorila:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
