version: '3.4'

services:
  ui:
    image: gorilaui
    build:
      context: .
      dockerfile: src/ui/Dockerfile
    ports:
      - '8081:8081'
    volumes:
      - ./src/ui:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  functions:
    image: gorilafunctions
    build:
      context: .
      dockerfile: src/function-app/Dockerfile
    ports:
      - '8080:80'
