name: Deploy to dev environment

on:
  push:
    branches: [dev]

jobs:
  deploy-frontend:
    name: Build and deploy frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/Gorila.UI
    steps:
      - name: 🚚 Get code
        uses: actions/checkout@v2

      - name: 📝 Replace .env tokens
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '__'
          tokenSuffix: '__'
          files: 'src/Gorila.UI/.env'
        env:
          API_URL: https://gorila-be.herokuapp.com
          FUNCTION_APP_URL: http://gorila.azurewebsites.net

      - name: 🔨 Build
        run: |
          npm install
          npm run build

      - name: 📂 Copy files through FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_GORILA_DEV_SERVER }}
          username: ${{ secrets.FTP_GORILA_DEV_USERNAME }}
          password: ${{ secrets.FTP_GORILA_DEV_PASSWORD }}
          local-dir: ./src/Gorila.UI/dist/

  deploy-function-app:
    name: Build and deploy Azure Function App ⚡
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/Gorila.FunctionApp
    env:
      AZURE_FUNCTIONAPP_NAME: gorila
      AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
      DOTNET_VERSION: '6.0'
    steps:
      - name: 🚚 Get code
        uses: actions/checkout@v2

      - name: 🤖 Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Resolve Project Dependencies Using Dotnet
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: Run Azure Functions Action
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
