name: Deploy to Hostinger

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  web-deploy:
    defaults:
      run:
        working-directory: web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: build
        run: npm run build
      - run: ls
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp://venenautica.com
          username: u578539920.ricardo
          password: u9&JEl>HeC
          local-dir: ./dist/
