name: Deploy to Hostinger

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  web-deploy:
    defaults:
      run:
        working-directory: web
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get code
        uses: actions/checkout@v2
      - name: 🔨 Build
        run: |
          npm install
          npm run build
      - name: 📂 Copy files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp://venenautica.com
          username: u578539920.ricardo
          password: ${{ secrets.FTP_PASSWORD }}
