name: Deploy to Hostinger

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd web
      - run: npm install
      - name: build
        run: npm run build
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp://venenautica.com
          username: u578539920.ricardo
          password: Jcjyg1wq-
          local-dir: ./dist/
          server-dir: public_html/
