name: Build and test app

on:
  pull_request:
    branches: [dev]

jobs:
  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/ui
    steps:
      - name: 🚚 Get code
        uses: actions/checkout@v2

      - name: 🔨 Build
        run: |
          npm install
          npm run build

  build-function-app:
    name: Build function app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/function-app
    env:
      AZURE_FUNCTIONAPP_NAME: gorila
      AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/function-app'
      DOTNET_VERSION: '6.0'
    steps:
      - name: 🚚 Get code
        uses: actions/checkout@v2

      - name: 🤖 Setup .NET ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 🔧 Install dependencies
        run: dotnet restore

      - name: 🔨 Build
        run: dotnet build --configuration Release --no-restore
